### ISSUE TITLE
Package is not being auto discovered

### ISSUE THREAD

**Issue by dacercoolex** [laravel-json-api/non-eloquent#2]
Hi!

I'm working in an implementation of a non-eloquent resource but, after installing the package through ``composer require laravel-json-api/non-eloquent`` it's not being auto discovered. I've been trying with different workarounds but without success so far.

Thanks in advance for any guidance to solve this issue.

Best regards!

**Comment by lindyhopchris** [comment]
Hi! Not sure what you mean by auto discovered? There's no service provider or facades to auto discover. Also, I have this in a production application and it's working fine. 

Can you be more specific about what isn't being auto discovered?

**Comment by dacercoolex** [comment]
Hi @lindyhopchris 

Yes, you're right, there's no service provider or facades, and in practice it's not much of a problem, but the thing is that, not being discovered by laravel after install, I'm not able to get vscode hints nor linkage when I call/use the different classes, and therefore, my code is full of error notices, even when there are not.

I don't know if I made myself clear, and this isn't by any mean a huge issue, but still it's kinda annoying, probable just for me, so I've opened the issue to get some enlightenment, whether for a workaround implementation in my code, or just to suck it up and keep working as it is.

I'm so sorry in advance if what I've brought has an easy solution I'm not able to see.

**Comment by lindyhopchris** [comment]
Hi! No problem raising this, but this is definitely an issue with VSCode. The package doesn't need to be auto-discovered by Laravel - all the autoloading of the classes is taken care of by Composer, so VSCode should recognise it as a dependency installed via Composer and in the `vendor` directory. That's what PHPStorm does.

I'm really surprised about this issue in VSCode, but I don't actually use VSCode for PHP as I use PHPStorm so not sure what to suggest. Maybe VSCode hasn't indexed the `vendor` directory correctly? If it's recognising classes from other packages installed via Composer, then something would seem to be wrong locally with your VSCode?

Sorry I can't help more.

**Comment by dacercoolex** [comment]
Thanks @lindyhopchris, that's just what I needed, check if it was something global or just me, and with your comments is enough for me to take local measures to correct -if any- issues on my development environment. 

Thanks again for your answer and your time!
